aq <- datasets::airquality

mean(aq$Ozone,na.rm=T)
median(aq$Ozone,na.rm=T)
var(aq$Ozone,na.rm=T)
sd(aq$Ozone,na.rm=T)
range(aq$Ozone,na.rm=T)
summary(aq$Ozone,na.rm=T)

mean(aq$Solar.R,na.rm=T)
median(aq$Solar.R,na.rm=T)
var(aq$Solar.R,na.rm=T)
sd(aq$Solar.R,na.rm=T)
range(aq$Solar.R,na.rm=T)
summary(aq$Solar.R,na.rm=T)

mean(aq$Wind,na.rm=T)
median(aq$Wind,na.rm=T)
var(aq$Wind,na.rm=T)
sd(aq$Wind,na.rm=T)
range(aq$Wind,na.rm=T)
summary(aq$Wind,na.rm=T)

mean(aq$Temp,na.rm=T)
median(aq$Temp,na.rm=T)
var(aq$Temp,na.rm=T)
sd(aq$Temp,na.rm=T)
range(aq$Temp,na.rm=T)
summary(aq$Temp,na.rm=T)

mean(aq$Month,na.rm=T)
median(aq$Month,na.rm=T)
var(aq$Month,na.rm=T)
sd(aq$Month,na.rm=T)
range(aq$Month,na.rm=T)
summary(aq$Month,na.rm=T)

mean(aq$Day,na.rm=T)
median(aq$Day,na.rm=T)
var(aq$Day,na.rm=T)
sd(aq$Day,na.rm=T)
range(aq$Day,na.rm=T)
summary(aq$Day,na.rm=T)

summary(aq,na.rm=T)
